### ISSUE TITLE
Ruby Upgrade Issue

### ISSUE THREAD

**Issue by josisusan** [tario/shikashi#28]
Hi,

Thanks for this awesome gem. I have been using your gem for 2 years without any issue. But lately when I upgraded my ruby to version 2.2.0, I encountered the following issue:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/josisusan/.rvm/rubies/ruby-2.2.0/bin/ruby -r ./siteconf20150303-99229-59ezm5.rb extconf.rb
    *** extconf.rb failed ***
     Could not create Makefile due to some reason, probably lack of necessary libraries and/or headers.  Check the mkmf.log file for more details.  You may need configuration options.

    Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/josisusan/.rvm/rubies/ruby-2.2.0/bin/$(RUBY_BASE_NAME)
	--with-getsource_base-dir
	--without-getsource_base-dir
	--with-getsource_base-include
	--without-getsource_base-include=${getsource_base-dir}/include
	--with-getsource_base-lib
	--without-getsource_base-lib=${getsource_base-dir}/lib
    extconf.rb:5:in `<main>': uninitialized constant Config (NameError)

    extconf failed, exit code 1

    Gem files will remain installed in /Users/josisusan/.rvm/gems/ruby-2.2.0/gems/getsource-0.2.1 for inspection.
    Results logged to /Users/josisusan/.rvm/gems/ruby-2.2.0/extensions/x86_64-darwin-14/2.2.0/getsource-0.2.1/gem_make.out
    An error occurred while installing getsource (0.2.1), and Bundler cannot continue.

**Comment by tario** [comment]
Thanks for the report, this bug should be reported to getsource gem also.
On shikashi, I will try to remove the dependency on getsource gem (or at least make it optional)

**Comment by tario** [comment]
I just fixed the bug, but I can't deploy the gem getsource to rubygems repository. You will need to download the gem here:  https://github.com/tario/getsource/archive/v0.2.2.zip . Use the command 

rake gem 

to generate the gem, and then install it using 

gem install getsource-0.2.2.gem

If you don't want to do that, you will have to wait until I can release the gem to rubygems gem repository

**Comment by tario** [comment]
I was able to deploy getsource to rubygems repository, update the gem by reinstalling shikashi gem, or doing "gem update getsource", the last version 0.2.2 of getsource should work on ruby 2.2.0 now.
PLease close this issue or report via comment if the fix works for you

**Comment by josisusan** [comment]
Thanks for your quick response. Its working fine right now.
